#!/usr/bin/python3 -u
#Note unbuffered output

import os, sys, subprocess, rtnl
from fnmatch import fnmatch
from time import sleep
from getopt import getopt

usage="""
Usage:

    autovlan [options] pattern [... pattern] vlanid

Given one or more glob-style network interface name patterns and a vlan id 1 to
4094, create a vlan for each matching interface.

Options are:

    -x pattern - interfaces that match this patterm will always be ignored. Can
    be used multiple times.
"""

reject={'lo'}
accept=set()

try:
    opts, args = getopt(sys.argv[1:],"x:")
    if len(args) < 2: raise Exception("Must specify at least one pattern and a vlan ID.")
    accept.update(args[:-1])
    vlanid=args[-1]
    assert 1 <= int(vlanid) <= 4094
    for opt, arg in opts:
        if opt == "-x": reject.add(arg)
except Exception as e:
    print (str(e), usage, file=sys.stderr)
    quit(1)

# return list of network interfaces, scraped from sysfs
def interfaces(): return os.listdir('/sys/class/net')

# execute the 'ip' command with given command line
def ip(cmd): return subprocess.call(["ip"] + cmd.split())

print("Applying vlan ID %s to interfaces that match %s but not %s" % (vlanid, str(accept)[1:-1], str(reject)[1:-1]))

vlan=set() # interfaces that we have vlan'd (or failed to)

nl=rtnl.rtnl(accept=accept, reject=reject)
nl.dump() # initially dump all existing interfaces

for event in nl.read():
    
    if not event: continue # ignore end of dump

    ifname = event["ifname"]
    attached = event["attached"]

    if not attached:
        vlan.discard(ifname)
    elif ifname not in vlan:
        v="vlan.%s" % ifname
        if v not in interfaces():
            print("Creating vlan %s" % v)
            # up the interface first
            if ip("link set dev %s up" % ifname):
                print("Could not bring %s up, ignoring it" % ifname)
            elif ip("link add link %s name %s type vlan id %s" % (ifname, v, vlanid)):
                print("Could not create %s, ignoring %s" % (v, ifname))
        else:
            print("Using existing vlan %s" % v)
        vlan.add(ifname)
