#!/usr/bin/python3 -u
# Note unbuffered output

import os, sys
from getopt import getopt
import subprocess
import rtnl

usage="""
Usage:

    autobridge [options] pattern [... pattern] bridge

Given one or more glob-style network interface name patterns and a bridge name,
create the bridge if necessary and add matching interfaces to it as they
appear.

Options are:

    -i ip.ad.re.ss/nm - specify static IP for the bridge.

    -x pattern - interfaces that match this patterm will always be ignored. Can
    be used multiple times.

    -u inteface - bridge will be down when the upstream interface is missing or
    doesn't have carrier.

"""

# execute the 'ip' command with given command line
def ip(cmd): return subprocess.call(["ip"] + cmd.split())

# parse command line param
bridge = sys.argv[-1]   # bridge name
reject={'lo', bridge}   # list of interfaces to ignore
accept=set()            # list of interfaces to be bridged
upstream=None           # upstream interface, if any
staticip=None           # static IP to apply to bridge, if any

try:
    opts, args = getopt(sys.argv[1:],"u:x:i:")
    if len(args) < 2: raise Exception("Must specify at least one pattern and a bridge name.")
    accept.update(args[:-1])
    bridge=args[-1]
    for opt, arg in opts:
        if opt == "-i":
            if staticip: raise Exception("Can't specify -i more than once.")
            staticip = arg
        elif opt == "-x":
            reject.add(arg)
        elif opt == "-u":
            if upstream: raise Exception("Can't specify -u more than once.")
            upstream = arg     # remember it
            accept.add(arg)    # also autobridge it

except Exception as e:
    print(str(e), usage, file=sys.stderr)
    quit(1)

print("Using bridge %s" % bridge)

# create the netlink object
nl=rtnl.rtnl()

# set bridge up or down
def upbridge(up):
    if up:
        print("Taking bridge up")
        if ip("link set dev %s up" % bridge): raise Exception("Could not up bridge")
    else:
        print("Taking bridge down")
        if ip("link set dev %s down" % bridge): raise Exception("Could not down bridge")

# add interface to bridge and set it up
def addbridge(ifname):
    print("Adding %s to bridge" % i.ifname)
    if ip("link set dev %s master %s up" % (i.ifname, bridge)):
        print("Could not add %s" % i.ifname)

print("Auto-bridging interfaces that match %s but not %s" % (str(accept)[1:-1], str(reject)[1:-1]))
if upstream: print("Upstream interface is %s" % upstream)

# scan existing devices
got=False       # found bridge device
isup=False      # upstream device is up
bridged=set()   # currently bridged interfaces

for i in nl.dump(accept=[accept,bridge], reject=reject):
    if i.ifname is bridge:
        got=True
    else:
        bridged.add(i.ifname)
        if i.ifname is upstream and i.carrier is not None: isup = i.up and i.carrier

if not got:
    print("Creating %s" % bridge)
    if ip("link add name %s type bridge" % bridge):
        raise Exception("Could not create bridge")

if staticip:
    print("Setting static IP %s" % staticip)
    ip("address flush dev %s" % bridge)
    if ip("address add %s dev %s" % (staticip, bridge)):
        raise Exception("Could not set bridge IP")

# init bridge up or down
upbridge(isup or not upstream)

# bridge existing interfaces
for i in bridged: addbridge(i)

# now wait for changes, this loops forever
for i in nl.wait(accept=accept, reject=reject):
    if not i.attached:
        # e.g. usb dongle unplugged
        bridged.discard(i.ifname)
    elif i.ifname not in bridged:
        # a new device
        bridged.add(i.ifname)
        addbridge(i.ifname)

    # bridge follows the state of the upstream device
    if i.ifname is upstream and i.carrier is not None:
        up = i.attached and i.carrier and i.up
        if up != isup:
            upbridge(up)
            isup=up
